# Generated by Django 4.1.7 on 2024-02-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='audio_visual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='building',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='computer_terminals',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='time_slot_id',
            field=models.IntegerField(default=0),
        ),
    ]
