# Generated by Django 4.1.7 on 2024-02-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0003_remove_event_audio_visual_remove_event_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'TimeSlot',
                'verbose_name_plural': 'TimeSlots',
                'ordering': ['-time_slot_id'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=300)),
                ('audio_visual', models.BooleanField(default=False)),
                ('computer_terminals', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['-venue_name'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='time_slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festmgmt.timeslot'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festmgmt.venue'),
        ),
    ]
