# Generated by Django 4.1.7 on 2024-02-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0004_timeslot_venue_alter_event_time_slot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
