# Generated by Django 4.1.7 on 2024-03-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0005_alter_timeslot_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useracc',
            options={'ordering': ['-user_id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organiser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='useracc',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='useracc',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useracc',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useracc',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useracc',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='useracc',
            name='last_name',
        ),
    ]
