# Generated by Django 4.1.7 on 2024-03-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0006_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festmgmt.event')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festmgmt.participant')),
            ],
            options={
                'verbose_name': 'Event_Winner',
                'verbose_name_plural': 'Event_Winners',
                'unique_together': {('event_id', 'participant_id')},
            },
        ),
    ]
