# Generated by Django 4.1.7 on 2024-03-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0006_volunteer'),
        ('festmgmt', '0007_alter_useracc_options_alter_admin_managers_and_more'),
    ]

    operations = [
    ]
