# Generated by Django 4.1.7 on 2024-03-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0007_event_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festmgmt.event')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festmgmt.participant')),
            ],
            options={
                'verbose_name': 'Participates',
                'verbose_name_plural': 'Participate',
                'unique_together': {('participant_id', 'event_id')},
            },
        ),
    ]
