# Generated by Django 4.1.7 on 2024-03-01 10:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0008_merge_20240301_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracc',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
