# Generated by Django 4.1.7 on 2024-03-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0008_participates'),
        ('festmgmt', '0009_alter_useracc_phone'),
    ]

    operations = [
    ]
