# Generated by Django 5.0.2 on 2024-03-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festmgmt', '0010_merge_0008_participates_0009_alter_useracc_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='accomodation_building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='accomodation_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
