CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "festmgmt_useracc" ("password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "user_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(300) NOT NULL, "email" varchar(300) NOT NULL UNIQUE, "phone" varchar(128) NOT NULL UNIQUE, "dob" date NULL, "gender" varchar(50) NULL, "username" varchar(300) NOT NULL UNIQUE, "collegeName" varchar(300) NOT NULL, "collegeLocation" varchar(300) NOT NULL, "role" varchar(40) NOT NULL);
CREATE TABLE IF NOT EXISTS "festmgmt_useracc_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "useracc_id" integer NOT NULL REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "festmgmt_useracc_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "useracc_id" integer NOT NULL REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "festmgmt_admin" ("useracc_ptr_id" integer NOT NULL UNIQUE REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "admin_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
CREATE TABLE IF NOT EXISTS "festmgmt_organiser" ("useracc_ptr_id" integer NOT NULL UNIQUE REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "organiser_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "position_of_responsibility" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "festmgmt_participant" ("useracc_ptr_id" integer NOT NULL UNIQUE REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "participant_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_external" bool NOT NULL, "food" varchar(100) NOT NULL, "accomodation_building" varchar(100) NOT NULL, "accomodation_room" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "festmgmt_student" ("useracc_ptr_id" integer NOT NULL UNIQUE REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "roll_number" varchar(50) NOT NULL PRIMARY KEY, "dept" varchar(100) NOT NULL, "year" integer NOT NULL);
CREATE UNIQUE INDEX "festmgmt_useracc_groups_useracc_id_group_id_ca113312_uniq" ON "festmgmt_useracc_groups" ("useracc_id", "group_id");
CREATE INDEX "festmgmt_useracc_groups_useracc_id_6113e3cb" ON "festmgmt_useracc_groups" ("useracc_id");
CREATE INDEX "festmgmt_useracc_groups_group_id_accd26d4" ON "festmgmt_useracc_groups" ("group_id");
CREATE UNIQUE INDEX "festmgmt_useracc_user_permissions_useracc_id_permission_id_cb46918a_uniq" ON "festmgmt_useracc_user_permissions" ("useracc_id", "permission_id");
CREATE INDEX "festmgmt_useracc_user_permissions_useracc_id_b716040e" ON "festmgmt_useracc_user_permissions" ("useracc_id");
CREATE INDEX "festmgmt_useracc_user_permissions_permission_id_51126e02" ON "festmgmt_useracc_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "festmgmt_useracc" ("user_id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "festmgmt_venue" ("venue_name" varchar(300) NOT NULL PRIMARY KEY, "building" varchar(300) NOT NULL, "audio_visual" bool NOT NULL, "computer_terminals" bool NOT NULL, "capacity" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "festmgmt_event" ("event_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "event_name" varchar(300) NOT NULL, "event_type" varchar(300) NOT NULL, "event_description" text NOT NULL, "time_slot_id_id" integer NOT NULL REFERENCES "festmgmt_timeslot" ("time_slot_id") DEFERRABLE INITIALLY DEFERRED, "venue_name_id" varchar(300) NOT NULL REFERENCES "festmgmt_venue" ("venue_name") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "festmgmt_event_time_slot_id_id_268e6ab4" ON "festmgmt_event" ("time_slot_id_id");
CREATE INDEX "festmgmt_event_venue_name_id_dc8c9006" ON "festmgmt_event" ("venue_name_id");
CREATE TABLE IF NOT EXISTS "festmgmt_timeslot" ("time_slot_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "start_time" datetime NOT NULL, "end_time" datetime NULL);
